KAFKA-1: ДЗ по "Кафка продюсер"
alekseiparamonov-volobuev/JavaSchool pull request #1
Opened 2024-12-21 14:38 UTC by alekseiparamonov-volobuev

2024-12-23 17:01 UTC, Liman26 requested changes

2024-12-23 17:01 UTC, Liman26 commented on producer/src/main/java/sbp/school/kafka/App.java
> +    public static void main(String[] args) {
В тесты, в исходниках только реализация

2024-12-23 17:01 UTC, Liman26 commented on producer/src/main/java/sbp/school/kafka/service/ProducerService.java
> +        producer.send(new ProducerRecord<>(transactionTopic, transaction.getOperationType().name(), transaction),
Если модуль экстренно завершит работу, последние сообщения будут отправлены?

2024-12-23 17:01 UTC, Liman26 commented on producer/src/main/java/sbp/school/kafka/utils/TransactionPartitioner.java
> +        OperationType.valueOf((String) key);
Лучше toString(), явное преобразование всегда потенциальные ошибки конвертирования

2024-12-23 17:01 UTC, Liman26 commented on producer/src/main/java/sbp/school/kafka/utils/TransactionSerializer.java
> +        return null;
Лучше не использовать практику возврата null. Это всегда потенциальный NPE. МОжно возвращать пустой массив или подбрасывать исключение

2024-12-24 17:43 UTC, alekseiparamonov-volobuev commented on producer/src/main/java/sbp/school/kafka/App.java
> +    public static void main(String[] args) {
подумал, что пока ок, т.к. занятие по тестирование - последнее)
перенёс

2024-12-24 17:45 UTC, alekseiparamonov-volobuev commented on producer/src/main/java/sbp/school/kafka/utils/TransactionPartitioner.java
> +        OperationType.valueOf((String) key);
\+

2024-12-24 17:53 UTC, alekseiparamonov-volobuev commented on producer/src/main/java/sbp/school/kafka/utils/TransactionSerializer.java
> +        return null;
я сам NPE и брошу

2024-12-24 18:02 UTC, alekseiparamonov-volobuev commented on producer/src/main/java/sbp/school/kafka/service/ProducerService.java
> +        producer.send(new ProducerRecord<>(transactionTopic, transaction.getOperationType().name(), transaction),
теперь очень надеюсь: добавил try catch с .flush()

2024-12-27 20:24 UTC, Liman26 commented on producer/src/main/java/sbp/school/kafka/App.java
> +    public static void main(String[] args) {
Там мы будем именно тесты писать, а здесь речь про отладочные данные

2024-12-27 20:25 UTC, Liman26 approved these changes

2025-01-22 17:32 UTC, merged