Feature/paramonov volobuev kafka 2
alekseiparamonov-volobuev/JavaSchool pull request #2
Opened 2024-12-22 14:20 UTC by alekseiparamonov-volobuev

2024-12-23 17:13 UTC, Liman26 requested changes

2024-12-23 17:13 UTC, Liman26 commented on consumer/src/main/java/sbp/school/kafka/service/ConsumerService.java
> +            log.error("Unexpected error or OutOfMemory", ex);
Все незакомиченные сообщения пропадут? Или будем по второму кругу вычитывать?

2024-12-23 17:13 UTC, Liman26 commented on producer/src/main/java/sbp/school/kafka/ProducerApp.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(10);
Ну раз уж многопоточный потребитель, давай его тоже конфигурировать

2024-12-27 20:30 UTC, Liman26 requested changes
Отметьте мои комментарии, которые поправлены

2024-12-27 20:30 UTC, Liman26 commented on consumer/src/main/java/sbp/school/kafka/service/ConsumerService.java
> +                    if (counter % 150 == 0) {
Магические числа? Что значит 150?

2025-01-22 18:51 UTC, alekseiparamonov-volobuev commented on consumer/src/main/java/sbp/school/kafka/service/ConsumerService.java
> +                    if (counter % 150 == 0) {
[B](https://refactoring.guru/replace-magic-number-with-symbolic-constant)
есть такое)

2025-01-22 18:57 UTC, alekseiparamonov-volobuev commented on consumer/src/main/java/sbp/school/kafka/service/ConsumerService.java
> +            log.error("Unexpected error or OutOfMemory", ex);
ну у нас транзакции, может быть проблемой повторная вычитка? Исправил (ещё не запушил)

2025-01-22 18:59 UTC, alekseiparamonov-volobuev commented on producer/src/main/java/sbp/school/kafka/ProducerApp.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(10);
на уровне producer.properties? или на уровне класса?

2025-01-23 02:23 UTC, Liman26 approved these changes

2025-01-23 02:23 UTC, Liman26 commented on consumer/src/main/java/sbp/school/kafka/service/ConsumerService.java
> +            log.error("Unexpected error or OutOfMemory", ex);
Для транзакций скорее всего на этапе обработки придется делать дополнительный коммит, это в любом случае вам решать на этапе проектирования. Здесь я вопросы подсветил на подумать

2025-01-23 02:23 UTC, Liman26 commented on producer/src/main/java/sbp/school/kafka/ProducerApp.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(10);
producer.properties - если надо будет поправить, чтобы обойтись без пересборки

2025-01-24 17:06 UTC, merged